apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::464194041274:role/eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::464194041274:role/AWSReservedSSO_SysAdmin-Test-Env_a46c1d19d1c0a596
      username: SysAdmin-Test-Env
      groups:
        - system:masters