apiVersion: v1
kind: Namespace
metadata:
  name: s3-managers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-managers-sa
  namespace: s3-managers
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::464194041274:role/eks-pod1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: s3-managers
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: webcontainer
    image: ubuntu:14.04

