apiVersion: v1
kind: Namespace
metadata:
  name: s3-managers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-managers-sa
  namespace: s3-managers
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::464194041274:role/eks-pod1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1-depl
  namespace: s3-managers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1-depl
  template:
    metadata:
      labels:
        app: pod1-depl
    spec:
      serviceAccountName: s3-managers-sa
      volumes:
      - name: html
        emptyDir: {}
      containers:
      - name: webcontainer
        image: ubuntu:14.04
        volumeMounts:
        - name: html
          mountPath: /html
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
             date >> /html/index.html;
             sleep 10;
            done

