apiVersion: v1
kind: Namespace
metadata:
  name: s3-managers
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: s3-managers
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: webcontainer
    image: ubuntu:14.04

