AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Launch Spinnaker infrastructure
Parameters:

  proj:
    Description: project name
    Type: String
  key:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  Responsible:
    Description: responsible person
    Type: String
  SgNames:
    Description: CommaDelimitedList of security group names
    Type: CommaDelimitedList

  VpcId:
    Description: _DEFAULT_ VPC Id
    Type: "AWS::EC2::VPC::Id"
  HalyardAmi:
    Description: AMI id
    Type: String
  HalyardSize:
    Description: instance type
    Type: String

# ===
Resources:
  Halyard:
    Type: 'AWS::EC2::Instance'

    Properties:
      SecurityGroups: !Ref SgNames
      ImageId: !Ref HalyardAmi
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: 'AWS::Region'
      UserData: !Base64
        'Fn::Sub': |
          #!/bin/bash -xe
          sed -i 's/^.* ssh-rsa /ssh-rsa /' /root/.ssh/authorized_keys
      KeyName: !Ref key
      InstanceType: !Ref HalyardSize
      IamInstanceProfile: !Ref HalyardRoleProf
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Halyard'
        - Key: Responsible
          Value: !Ref Responsible

  BaseIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BaseIAMRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: [ "sts:AssumeRole" ]
            Principal:
              Service: [ "ec2.amazonaws.com" ]
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                 - 'ec2:*'
                 - 'ecr:*'
                 - 'cloudformation:*'
                 - 's3:*'
                Resource: '*'

  HalyardRoleProf:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref BaseIAMRole

# ===
Outputs:
  halyardIp:
    Value: !GetAtt Halyard.PublicIp
    Description: Halyard.PublicIp